services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: rpg_helper
      POSTGRES_USER: rpg_helper_db_user
      POSTGRES_PASSWORD: rpg_helper_db_password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
